<?php
namespace app\admin\controller;

use think\Controller;
use think\Hook;
use think\auth\Auth;

class Base extends Controller
{
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        Hook::listen('CheckAuth', $params);
    }
}
